version: '3.5'

services:
  library:
    container_name: library
    image: mongo:6
    restart: always
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_DATABASE: library
    volumes:
      - ./mongodata/dev:/data/db
      - ./packages/database/src/infrastructure/persistence/mongo/initDatabase.js:/docker-entrypoint-initdb.d/initDatabase.js
    networks:
      - network-interface

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    restart: always
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      RABBITMQ_DEFAULT_USER: library
      RABBITMQ_DEFAULT_PASS: library
    networks:
      - network-interface

  redis:
    image: redis:7.2-alpine
    container_name: redis
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - network-interface

  grafbase-gateway:
    image: ghcr.io/grafbase/gateway:latest
    container_name: grafbase-gateway
    ports:
      - '4001:4001'
      - '9668:9668'
    volumes:
      - ./packages/graphql-gateway/supergraph.graphql:/app/supergraph.graphql:ro
      - ./packages/graphql-gateway/grafbase.toml:/app/grafbase.toml:ro
    command:
      - --config
      - /app/grafbase.toml
      - --schema
      - /app/supergraph.graphql
      - --listen-address
      - 0.0.0.0:4001
    restart: unless-stopped
    networks:
      - network-interface

volumes:
  redis_data:

networks:
  network-interface:
    driver: bridge
