version: '3.5'
services:
  library:
    container_name: library
    image: mongo:6
    restart: always
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_DATABASE: library
    volumes:
      - ./mongodata/dev:/data/db
      - ./packages/database/src/mongo/initDatabase.js:/docker-entrypoint-initdb.d/initDatabase.js

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    restart: always
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      RABBITMQ_DEFAULT_USER: library
      RABBITMQ_DEFAULT_PASS: library

  redis:
    image: redis:7.2-alpine
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  redis_data:
