# Graph configuration
[graph]
introspection = true
# Consider disabling introspection in production environments
# introspection = false
path = "/graphql"
websocket_path = "/ws"

# Authentication
[authentication]
default = "anonymous"

# Automatic persisted queries (APQ)
[apq]
enabled = true

# CORS
[cors]
allow_credentials = false
# allow_origins = ["*"]
max_age = "60s"
allow_methods = ["GET", "POST"]
allow_headers = ["Content-Type"]
expose_headers = ["Access-Control-Allow-Origin"]
allow_private_network = false

# CSRF
[csrf]
enabled = false

# Complexity control
[complexity_control]
mode = "enforce"
limit = 10000
list_size = 100

# Entity caching
[entity_caching.redis]
url = "redis://redis:6379"
key_prefix = "graphql-gateway-cache"

# [entity_caching.redis.tls]
# cert = "/path/to/user.crt"
# key = "/path/to/user.key"
# ca = "/path/to/ca.crt"

# Gateway
[gateway]
timeout = "30s"
subgraph_timeout = "4s"

# Rate limit
[gateway.rate_limit]
storage = "redis"

# Global rate limit
[gateway.rate_limit.global]
limit = 100
duration = "10s"

# Redis rate limit
[gateway.rate_limit.redis]
url = "redis://redis:6379"
key_prefix = "graphql-gateway-rate-limit"

# Redis rate limit TLS
# [gateway.rate_limit.redis.tls]
# cert = "/path/to/user.crt"
# key = "/path/to/user.key"
# ca = "/path/to/ca.crt"

# Batching
[gateway.batching]
enabled = false
limit = 5

# Retry
[gateway.retry]
enabled = true
min_per_second = 10
ttl = "1s"
retry_percent = 0.1
retry_mutations = false

# Access logs
# ToDo: https://grafbase.com/docs/features/security/access-logs
[gateway.access_logs]
enabled = false
path = "/var/log/"
rotate = "daily"
mode = "blocking"

# Headers
# https://grafbase.com/docs/reference/gateway/configuration/header-rules
[[headers]]
rule = "forward"
name = "authorization"

# Healthcheck
[health]
enabled = true
listen = "0.0.0.0:9668"
path = "/health/liveness"

# Operation limits
[operation_limits]
depth = 10
height = 12
aliases = 5
root_fields = 6
complexity = 100

# Operation caching
[operation_caching]
enabled = true
limit = 1000
warm_on_reload = false
warming_percent = 100

# Operation caching Redis
# [operation_caching.redis]
# url = "redis://redis:6379"
# key_prefix = "my_gateway"

# [operation_caching.redis.tls]
# cert = "/path/to/user.crt"
# key = "/path/to/user.key"
# ca = "/path/to/ca.crt"

# Telemetry
# ToDo: https://grafbase.com/docs/reference/gateway/configuration/telemetry
[telemetry]
service_name = "graphql-gateway"

# TLS
# ToDo: https://grafbase.com/docs/reference/gateway/configuration/transport-layer-security
# [tls]
# certificate = "/path/to/cert.pem"
# key = "/path/to/key.pem"
