/**
 * Domain event types for the Reservation aggregate.
 */
export const RESERVATION_CREATED = 'RESERVATION_CREATED'
export const RESERVATION_UPDATED = 'RESERVATION_UPDATED'
export const RESERVATION_CANCELLED = 'RESERVATION_CANCELLED'
export const RESERVATION_RETURNED = 'RESERVATION_RETURNED'
export const RESERVATION_DELETED = 'RESERVATION_DELETED'
export const RESERVATION_OVERDUE = 'RESERVATION_OVERDUE'
export const RESERVATION_PENDING_PAYMENT = 'RESERVATION_PENDING_PAYMENT'
export const RESERVATION_CONFIRMED = 'RESERVATION_CONFIRMED'
export const RESERVATION_REJECTED = 'RESERVATION_REJECTED'
export const RESERVATION_BOOK_VALIDATION = 'RESERVATION_VALIDATE_BOOK'
export const RESERVATION_BOOK_LIMIT_REACH = 'RESERVATION_BOOK_LIMIT_REACH'
export const RESERVATION_RETAIL_PRICE_UPDATED =
  'RESERVATION_RETAIL_PRICE_UPDATED'

/**
 * TypeScript type for the Reservation event types.
 */
export type ReservationEventType =
  | typeof RESERVATION_CREATED
  | typeof RESERVATION_UPDATED
  | typeof RESERVATION_CANCELLED
  | typeof RESERVATION_RETURNED
  | typeof RESERVATION_DELETED
  | typeof RESERVATION_OVERDUE
  | typeof RESERVATION_PENDING_PAYMENT
  | typeof RESERVATION_CONFIRMED
  | typeof RESERVATION_REJECTED
  | typeof RESERVATION_BOOK_VALIDATION
  | typeof RESERVATION_RETAIL_PRICE_UPDATED
